export enum PaymentStatus {
  PAID = 'PAID',
  PENDING = 'PENDING',
  FAILED = 'FAILED',
}

export enum ResponseCode {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  GENERIC_ERROR = 'GENERIC_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INPUT_ERROR = 'INPUT_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  DATABASE_ERROR = 'DATABASE_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
